# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

# BaseURL: this should include the Hostname and Path (if any) where the site
# will live when it is built. If your baseurl includes a path component
# (i.e. "/canto-catalogue/" in the example below) then you can preview the
# site at localhost:1313/canto-catalogue/ when running the server.
#
# If your baseURL only has a host-name ("http://my-awesome-site.com/") then
# you'll preview it at localhost:1313.
#
baseurl: "https://gettypubs.github.io/canto-catalogue"

title: "Canto Catalogue Demo"
languageCode: "en-us"
theme: "canto-catalogue-theme"
footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
canonifyURLs: true

# Menu: the 'main' menu will be picked up in the sidebar navigation menu in the
# default theme. Other menus can be defined here as well for use with custom
# theme files. To control order, give items a weight; lower numbers will appear
# first. Negative values are allowed.
#
menu:
  main:
    - Name: "Contents"
      URL: "/contents/"
      weight: 1
    - Name: "Catalogue"
      URL: "/catalogue/"
      weight: 2
    - Name: "Bibliography"
      URL: "/bibliography/"
      weight: 3
    - Name: "About"
      URL: "/about/"
      weight: 4
