# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. Make sure to change the
# values for 'baseurl' to wherever your site will live. 'theme' should match the
# name of the folder in /themes that contains your theme files; if you've
# copied the default theme and given it a different name make sure to update the
# value here too.
#
baseurl: "http://replace-this-with-your-hugo-site.com/"
title: "Canto Example Site"
languageCode: "en-us"
theme: "canto-catalogue-theme"
footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"

# Menu: the 'main' menu will be picked up in the sidebar navigation menu in the
# default theme. Other menus can be defined here as well for use with custom
# theme files. To control order, give items a weight; lower numbers will appear
# first. Negative values are allowed.
menu:
  main:
    - Name: "Contents"
      URL: "/contents/"
      weight: 1
    - Name: "Catalogue"
      URL: "/catalogue/"
      weight: 2
    - Name: "Bibliography"
      URL: "/bibliography/"
      weight: 3
    - Name: "About"
      URL: "/about/"
      weight: 4

