# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

# Use these settings for serving/building to a path other than root
# baseURL: "https://gettypubs.github.io/artistryinbronze"
# canonifyURLs: true

# Use these settings for serving/building to the root path
baseURL: ""
relativeURLs: true

theme: "quire-base-theme"
footnoteReturnLinkContents: "↥"
# footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"



blackfriday:
  fractions: false

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  imageLabelContentBefore: "Figure "
  imageLabelContentAfter: ". "
  tableLabelContentBefore: "Table "
  tableLabelContentAfter: ". "
  primaryColor: "#995326"
  tocType: "full"
  menuType:  "short"
